version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: eighty-two-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: logindemo
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eighty-two-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eighty-two-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/logindemo?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - eighty-two-network

  # Vue Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: eighty-two-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - eighty-two-network

volumes:
  mysql_data:

networks:
  eighty-two-network:
    driver: bridge 