openapi: 3.0.3
info:
  title: Care Scheduling API
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /api/auth/login:
    post:
      summary: User login
      description: Authenticate a user with username and password, return JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  format: password
                  example: admin123
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "401":
          description: Unauthorized (invalid username or password)